name: Update Followers and Stars

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch GitHub Data
        id: fetch_data
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/rdas28 | jq '.followers')
          STARS=$(curl -s https://api.github.com/users/rdas28/repos?per_page=100 | jq '[.[] | .stargazers_count] | add')

          if [ -z "$FOLLOWERS" ] || [ "$FOLLOWERS" = "null" ]; then
            FOLLOWERS=0
          fi

          if [ -z "$STARS" ] || [ "$STARS" = "null" ]; then
            STARS=0
          fi

          echo "FOLLOWERS_COUNT=${FOLLOWERS}" >> $GITHUB_ENV
          echo "STARS_COUNT=${STARS}" >> $GITHUB_ENV

      - name: Replace Placeholders in README.md
        run: |
          sed -i "s/{{FOLLOWERS_COUNT}}/$FOLLOWERS_COUNT/g" README.md
          sed -i "s/{{STARS_COUNT}}/$STARS_COUNT/g" README.md

      - name: Debug Placeholder Replacement
        run: cat README.md
