name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Data
        id: fetch_data
        run: |
          # Fetch followers count
          FOLLOWERS=$(curl -s https://api.github.com/users/rdas28 | jq '.followers')

          # Fetch stars count (sum of all repos' stars)
          STARS=$(curl -s https://api.github.com/users/rdas28/repos?per_page=100 | jq '[.[] | .stargazers_count] | add')

          # Handle null or missing values
          if [ -z "$FOLLOWERS" ] || [ "$FOLLOWERS" = "null" ]; then
            FOLLOWERS=0
          fi

          if [ -z "$STARS" ] || [ "$STARS" = "null" ]; then
            STARS=0
          fi

          echo "FOLLOWERS_COUNT=${FOLLOWERS}" >> $GITHUB_ENV
          echo "STARS_COUNT=${STARS}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/{{ FOLLOWERS_COUNT }}/$FOLLOWERS_COUNT/g" README.md
          sed -i "s/{{ STARS_COUNT }}/$STARS_COUNT/g" README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update followers and stars count"
          git push

